name: build

on: 
  push:
    branches:
    - master
    paths:
    - database/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: init git config
      run: |
        git config --global user.email '66814738+ehtagtranslation[bot]@users.noreply.github.com'
        git config --global user.name  'ehtagtranslation[bot]'
    - name: Install node modules
      uses: bahmutov/npm-install@v1
      with:
          working-directory: ./tools
    - name: Create token
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_KEY: ${{ secrets.APP_KEY }}
        APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
        APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
        APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
      run: node ./tools/gen-token.js
        
    - name: Download tool
      uses: fabriciobastian/download-release-asset-action@v1.0.6
      with:
        repository: EhTagTranslation/Editor
        file: release.zip
    - name: Build
      run: |
        unzip release.zip -d build-tool
        cd build-tool
        yarn start --source .. --target ../publish
    - name: Set messages
      run: |
        echo "::set-env name=RELEASE_NAME::$(
        head -n1 <<EOF
        ${{github.event.head_commit.message}}
        EOF
        )"
    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./publish/*
        body: |
          ${{github.event.before}}...${{github.event.after}}
          
          ${{github.event.head_commit.message}}
        token: ${{ env.APP_TOKEN }}
        commit: ${{ github.sha }}
        tag: ${{ format('v-{0}', github.sha) }}
        name: ${{ env.RELEASE_NAME }}
    - name: Commit release branch
      run: > 
        cd ./publish
        && (printf '${{ github.sha }}' > ./sha)
        && git init
        && git add .
        && git commit -am 'Release for https://github.com/EhTagTranslation/Database/commit/${{ github.sha }}'
    - name: Push release branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ env.APP_TOKEN }}
        force: true
        directory: ./publish
        repository: EhTagTranslation/DatabaseReleases
    - name: Clean releases
      env:
        GITHUB_TOKEN: ${{ env.APP_TOKEN }}
      run: node ./tools/delete-old-releases.js
 
